### ISSUE TITLE
mac local or web also

### ISSUE THREAD

**Issue by amirmog** [hbouvier/node-tts#1]
Wll this only run on local mac or can i expose this (along with the voices) to the web as well (ie. using a node web-hosting)?
Thanks for the great work

**Comment by hbouvier** [comment]
Hi amirmog,

This project is meant to be a WebService to generate Text To Speech (TTS) and stream back the audio in a web friendly format.

The "sample" code under "www" was provided to show how to use locally. I changed it to support using that page from another server (e.g. not from localhost). However, when I use it, in web page, I use the WS api directly:

   http://MyServerName:8082/tts/ws/play?text=hello+from+node&voice=Kathy

Hope it will be useful,

```
  Henri
```
